### PR TITLE
Responsive design for mobile screens #30

### PR DESCRIPTION
**Pull request by sravan7**
Adds Responsive design for mobile screens #30

### CODE REVIEW

**Comment by alexnm** [comment]
@sravan7 thanks for the PR! the solution looks good, however, please pull the upstream master into your fork as there were a couple of changes to the UI in the past few days.

**Comment by sravan7** [comment]
> @sravan7 thanks for the PR! the solution looks good, however, please pull the upstream master into your fork as there were a couple of changes to the UI in the past few days.

completed.

**Comment by alexnm** [comment]
@sravan7 sorry for the mixup, just saw now, your PR should go to master, not development. That's why I was seeing the old UI. can you please redo the PR from your branch to the master branch of this project?

**Comment by sravan7** [comment]
> @sravan7 sorry for the mixup, just saw now, your PR should go to master, not development. That's why I was seeing the old UI. can you please redo the PR from your branch to the master branch of this project?

@alexnm Completed.  sorry It was my mistake I am new to PRs

**Pull request closed without merging**
